# Generated by Django 5.2.17 on 2026-09-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="team/")),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower numbers appear first)"
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
