# Generated by Django 5.2.17 on 2026-09-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team_members", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teammember",
            name="role",
        ),
        migrations.AddField(
            model_name="teammember",
            name="role_de",
            field=models.CharField(default="", max_length=255, verbose_name="Role (German)"),
        ),
        migrations.AddField(
            model_name="teammember",
            name="role_en",
            field=models.CharField(default="", max_length=255, verbose_name="Role (English)"),
        ),
    ]
