# Generated by Django 5.2.17 on 2026-09-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage_elements", "0002_postshowselement_preshowselement"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroImageElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to="hero_images/")),
                ("active", models.BooleanField(default=False)),
            ],
        ),
    ]
