# Generated by Django 5.2.17 on 2026-09-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage_elements", "0003_heroimageelement"),
    ]

    operations = [
        migrations.AddField(
            model_name="heroimageelement",
            name="mobile_image",
            field=models.ImageField(blank=True, null=True, upload_to="hero_images/mobile/"),
        ),
    ]
