services:
  postgres:
    image: postgres:16.1
    container_name: staging_postgres
    restart: always
    volumes:
      - zm_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=monddb
      - POSTGRES_USER=mond
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  redis:
    image: redis:7-alpine
    container_name: staging_redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - zm_redis:/data

  zm:
    hostname: staging_zirkusmond_de
    image: ${DOCKER_USERNAME}/zirkusmond:staging
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - zm_media:/srv/data
    depends_on:
      - postgres
      - redis

  celery_worker:
    image: ${DOCKER_USERNAME}/zirkusmond:staging
    container_name: staging_celery_worker
    working_dir: /usr/src/backend
    command: celery -A config worker --loglevel=info
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

  celery_beat:
    image: ${DOCKER_USERNAME}/zirkusmond:staging
    container_name: staging_celery_beat
    working_dir: /usr/src/backend
    command: celery -A config beat --loglevel=info
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

networks:
  default:
    external: true
    name: ubuntu_default

volumes:
  zm_media:
  zm_db:
  zm_redis:
