# Generated by Django 5.2.15 on 2026-07-27 09:46

from django.db import migrations, models


def deduplicate_emails(apps, schema_editor):
    Model = apps.get_model("newsletter", "NewsletterSubscription")
    seen = set()
    for obj in Model.objects.order_by("id"):
        if obj.email in seen:
            obj.delete()
        else:
            seen.add(obj.email)


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0002_alter_newslettersubscription_id"),
    ]

    operations = [
        migrations.RunPython(deduplicate_emails, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="newslettersubscription",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
