# Generated by Django 5.2.17 on 2026-09-28 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0003_alter_newsletterregistration_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletterregistration",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
