# Generated by Django 5.2.17 on 2026-09-29 09:42

from django.db import migrations


def create_subscription_table(apps, schema_editor):
    """Create the newslettersubscription table if it doesn't exist."""
    db_alias = schema_editor.connection.alias
    is_sqlite = schema_editor.connection.vendor == "sqlite"

    with schema_editor.connection.cursor() as cursor:
        # Create the table if it doesn't exist (SQLite vs PostgreSQL syntax)
        if is_sqlite:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS newsletter_newslettersubscription (
                    id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                    email varchar(254) NOT NULL UNIQUE,
                    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
            """)
        else:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS newsletter_newslettersubscription (
                    id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    email varchar(254) NOT NULL UNIQUE,
                    created_at timestamp with time zone NOT NULL DEFAULT NOW()
                )
            """)


def copy_data_to_subscription(apps, schema_editor):
    """Copy data from newsletterregistration to newslettersubscription."""
    db_alias = schema_editor.connection.alias
    is_sqlite = schema_editor.connection.vendor == "sqlite"

    with schema_editor.connection.cursor() as cursor:
        # Check if old table exists and has data
        if is_sqlite:
            cursor.execute("""
                SELECT name FROM sqlite_master
                WHERE type='table' AND name='newsletter_newsletterregistration'
            """)
            table_exists = cursor.fetchone() is not None
        else:
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables
                    WHERE table_schema = 'public'
                    AND table_name = 'newsletter_newsletterregistration'
                )
            """)
            table_exists = cursor.fetchone()[0]

        if table_exists:
            # Copy data from old table to new table
            if is_sqlite:
                cursor.execute("""
                    INSERT OR IGNORE INTO newsletter_newslettersubscription (id, email, created_at)
                    SELECT id, email, created_at
                    FROM newsletter_newsletterregistration
                """)
            else:
                cursor.execute("""
                    INSERT INTO newsletter_newslettersubscription (id, email, created_at)
                    SELECT id, email, created_at
                    FROM newsletter_newsletterregistration
                    ON CONFLICT (email) DO NOTHING
                """)

            # Update the sequence to the max ID to avoid conflicts (PostgreSQL only)
            if not is_sqlite:
                cursor.execute("""
                    SELECT setval(
                        'newsletter_newslettersubscription_id_seq',
                        COALESCE((SELECT MAX(id) FROM newsletter_newslettersubscription), 1),
                        true
                    )
                """)


def reverse_migration(apps, schema_editor):
    """No reverse operation needed - keep the data."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0004_newsletterregistration_created_at"),
    ]

    operations = [
        migrations.RunPython(create_subscription_table, reverse_migration),
        migrations.RunPython(copy_data_to_subscription, reverse_migration),
    ]
